name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      cassandra:
        image: cassandra:3.11
        ports:
          - 9042:9042
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Use Python 3.11 instead of 3.12

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libffi-dev build-essential

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Run Tests
        shell: bash
        run: |
          python -m pytest


  # deploy:
  #   name: Deploy to DigitalOcean
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Set up SSH Agent
  #       uses: webfactory/ssh-agent@v0.8.1
  #       with:
  #         ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}

  #     - name: Deploy Application
  #       run: |
  #         ssh -o StrictHostKeyChecking=no user@${{ secrets.DROPLET_IP }} <<EOF
  #         cd /root/padlab4
  #         docker-compose down
  #         git pull origin main
  #         docker-compose up -d --build
  #         EOF
